"""``web build``: render the site into a fresh ``--out`` directory.

Read-only on its inputs (AC-A3): the DB is opened ``mode=ro`` and nothing is written beside the
DB or the manifest. An ``--out`` that exists and is not empty is refused before anything is
written (exit 2). The site is staged in ``<out>/.staging-<pid>`` and its contents moved up into
``<out>`` only when complete, so nothing is ever written or deleted outside ``--out``; on error
the staging dir is removed (and ``<out>`` too when this build created it).

Writes the data layer (``data/*.json``, the per-page ``items.json``), every HTML page
(``pages.py``), the static assets (CSS with a content hash, fonts, and the ``web/dist`` JS
bundle when it has been built), ``sitemap.xml``, ``robots.txt``, ``changes.xml``,
``_headers`` and ``web-manifest.json``. With ``media`` (a ``web/media`` folder) it also copies
the member photos and organisation logos (``media.py``) and writes ``og-cards.json``, the spec
of every page's Open Graph card, which ``web/scripts/og-cards.mjs`` renders to PNG for R2.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import json
import os
import shutil
from pathlib import Path
from typing import Dict, Optional, Tuple
from urllib.parse import urlsplit

from . import WEB_BUNDLE_VERSION
from . import metadata as MD
from .bundle import dumps, write, write_data
from .dataset import Dataset, sha256_file
from .media import MediaError, copy_media

MODES = ("preview", "production")
DEFAULT_DATA_BASE = "https://data.kevinrassool.com/interests/"
DEFAULT_SITE_URL = "https://interests.kevinrassool.com"
MANIFEST_NAME = "web-manifest.json"
HEADERS_NAME = "_headers"
ASSETS_DIR = "assets"  # content-hashed JS/CSS; cached for a year
MEDIA_DIR = "media"    # content-hashed photos and logos; cached for a year
OG_CARDS = "og-cards.json"
# Bump when the card design changes: the og:image URLs change with it, so social sites that
# cache previews by URL fetch the new card.
OG_CARD_VERSION = 1
FONTS_DIR = "fonts"
STATIC_DIR = Path(__file__).parent / "static"
WEB_DIST = Path(__file__).resolve().parents[2] / "web" / "dist"
MiB = 1024 * 1024
MAX_FILES = 12_000
MAX_TOTAL = 300 * MiB


class BuildError(ValueError):
    """Bad input, clobber guard or a site over the size limits (exit 2)."""


def render_headers(mode: str) -> str:
    """Cloudflare ``_headers``: CORS on the static API, long cache on hashed assets, and
    ``noindex`` on every path in preview mode."""
    lines = [f"# Generated by python -m disclosures web build (mode: {mode}). Do not edit."]
    if mode == "preview":
        lines += ["/*", "  X-Robots-Tag: noindex, nofollow"]
    lines += [
        "/data/*", "  Access-Control-Allow-Origin: *",
        "/*/items.json", "  Access-Control-Allow-Origin: *",
        f"/{ASSETS_DIR}/*", "  Cache-Control: public, max-age=31536000, immutable",
        f"/{MEDIA_DIR}/*", "  Cache-Control: public, max-age=31536000, immutable",
    ]
    return "\n".join(lines) + "\n"


def file_index(root: Path, exclude=(MANIFEST_NAME,)) -> dict:
    """rel path -> {sha256, size} for every file under ``root``, sorted."""
    out = {}
    for p in sorted(root.rglob("*")):
        if p.is_file():
            rel = p.relative_to(root).as_posix()
            if rel in exclude:
                continue
            data = p.read_bytes()
            out[rel] = {"sha256": hashlib.sha256(data).hexdigest(), "size": len(data)}
    return out


def build_time() -> str:
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    t = (dt.datetime.fromtimestamp(int(epoch), dt.timezone.utc) if epoch
         else dt.datetime.now(dt.timezone.utc))
    return t.isoformat(timespec="seconds")


def _check_out(out: Path) -> None:
    if out.exists():
        if not out.is_dir():
            raise BuildError(f"--out {out} exists and is not a directory")
        if any(out.iterdir()):
            raise BuildError(f"--out {out} exists and is not empty; refusing to overwrite")


def _check_data_base(data_base: str) -> None:
    u = urlsplit(data_base)
    if u.scheme not in ("http", "https") or not u.netloc or not data_base.endswith("/"):
        raise BuildError(f"--data-base must be an http(s) URL ending in '/': {data_base!r}")


def _check_site_url(site_url: str) -> str:
    u = urlsplit(site_url)
    if u.scheme not in ("http", "https") or not u.netloc or u.query or u.fragment or \
            u.path.strip("/"):
        raise BuildError(f"--site-url must be an http(s) origin such as {DEFAULT_SITE_URL}: "
                         f"{site_url!r}")
    return f"{u.scheme}://{u.netloc}"


def _check_doi(doi: Optional[str]) -> Optional[str]:
    if doi is None:
        return None
    d = doi.strip()
    for prefix in ("https://doi.org/", "http://doi.org/", "doi:"):
        if d.lower().startswith(prefix):
            d = d[len(prefix):]
    if not d.startswith("10.") or "/" not in d or any(c.isspace() for c in d):
        raise BuildError(f"--doi must look like 10.<registrant>/<suffix>: {doi!r}")
    return d


def _hashed(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()[:8]


def copy_assets(stage: Path, web_dist: Path = WEB_DIST) -> Tuple[str, Dict[str, str]]:
    """Copy the CSS (content-hashed), fonts and any built JS into the site.

    Returns (CSS href, {JS entry name: href}). JS is optional: without ``web/dist`` (a CI
    runner without Node) every page still renders, minus the progressive enhancements.
    """
    css = (STATIC_DIR / "style.css").read_bytes()
    css_rel = f"{ASSETS_DIR}/style.{_hashed(css)}.css"
    write(stage, css_rel, css)
    for f in sorted((STATIC_DIR / "fonts").iterdir()):
        if f.suffix in (".woff2", ".txt"):
            write(stage, f"{FONTS_DIR}/{f.name}", f.read_bytes())
    js: Dict[str, str] = {}
    if web_dist.is_dir():
        for f in sorted(web_dist.glob("*.js")):
            data = f.read_bytes()
            rel = f"{ASSETS_DIR}/{f.stem}.{_hashed(data)}.js"
            write(stage, rel, data)
            js[f.stem] = "/" + rel
    return "/" + css_rel, js


def _measure(root: Path) -> Tuple[int, int, int, int]:
    """(files, bytes, html files, html bytes) under root."""
    n = size = n_html = html = 0
    for p in root.rglob("*"):
        if p.is_file():
            s = p.stat().st_size
            n, size = n + 1, size + s
            if p.suffix == ".html":
                n_html, html = n_html + 1, html + s
    return n, size, n_html, html


def build(db: str | Path, manifest: str | Path, out: str | Path, mode: str = "preview",
          data_base: str = DEFAULT_DATA_BASE, site_url: str = DEFAULT_SITE_URL,
          doi: Optional[str] = None, data_files: str | Path | None = None,
          web_dist: str | Path | None = None, media: str | Path | None = None,
          og_base: Optional[str] = None) -> dict:
    """Build the site. ``data_files`` is an optional local folder holding the R2 data files
    (e.g. a ``publish-data`` output); when given, ``/data/`` prints their sizes and sha256.
    ``media`` is the ``web/media`` folder (photos, logos, ``media.json``); without it pages
    have no images. ``og_base`` is where the Open Graph cards are served (default
    ``<data_base>og/<dataset version>.c<OG_CARD_VERSION>/``)."""
    from .pages import SiteConfig, render_site

    db, manifest, out = Path(db), Path(manifest), Path(out)
    if mode not in MODES:
        raise BuildError(f"--mode must be one of {MODES}")
    _check_data_base(data_base)
    site_url = _check_site_url(site_url)
    doi = _check_doi(doi)
    data_files = Path(data_files) if data_files is not None else None
    if data_files is not None and not data_files.is_dir():
        raise BuildError(f"--data-files {data_files} is not a directory")
    media = Path(media) if media is not None else None
    if media is not None and not (media / "media.json").is_file():
        raise BuildError(f"--media {media} has no media.json")
    if og_base is not None:
        _check_data_base(og_base)
    _check_out(out)
    with Dataset(db, manifest) as ds:
        # Fail on bad input (missing URL, unsafe id) before touching the filesystem.
        ds.documents()
        ds.members()
        ds.entities()
        created = not out.exists()
        out.mkdir(parents=True, exist_ok=True)
        stage = out / f".staging-{os.getpid()}"
        stage.mkdir()
        try:
            stats = write_data(ds, stage)
            css_href, js = copy_assets(stage, Path(web_dist) if web_dist else WEB_DIST)
            summary_meta = ds.meta()
            try:
                images = copy_media(media, stage, [m["id"] for m in ds.members()],
                                    [e["id"] for e in ds.entities() if e["page"]])
            except (MediaError, KeyError, OSError, ValueError) as e:
                raise BuildError(f"--media: {e}") from e
            og_base = og_base or (f"{data_base}og/{MD.dataset_version(summary_meta)}"
                                  f".c{OG_CARD_VERSION}/")
            cfg = SiteConfig(mode=mode, site_url=site_url, data_base=data_base, doi=doi,
                             css_href=css_href, js=js, data_files=data_files, media=images,
                             og_base=og_base)
            pages, cards = render_site(ds, stage, cfg)
            write(stage, OG_CARDS, dumps({"og_base": og_base, "width": 1200, "height": 630,
                                          "cards": cards}, pretty=True))
            summary = json.loads((stage / "data" / "summary.json").read_text(encoding="utf-8"))
            write(stage, "sitemap.xml",
                  MD.sitemap_xml(site_url, pages, summary.get("data_date")).encode("utf-8"))
            write(stage, "robots.txt", MD.robots_txt(mode, site_url).encode("utf-8"))
            write(stage, "changes.xml",
                  MD.changes_xml(site_url, summary, summary_meta).encode("utf-8"))
            write(stage, HEADERS_NAME, render_headers(mode).encode("utf-8"))
            files = file_index(stage)
            manifest_doc = {
                "web_bundle_version": WEB_BUNDLE_VERSION,
                "mode": mode,
                "built_at": build_time(),
                "data_base": data_base,
                "site_url": site_url,
                "doi": doi,
                "og_base": og_base,
                "dataset_version": MD.dataset_version(summary_meta),
                "inputs": {
                    "db": {"name": db.name, "sha256": ds.db_sha256, "size": db.stat().st_size},
                    "manifest": {"name": manifest.name, "sha256": ds.manifest_sha256,
                                 "size": manifest.stat().st_size},
                },
                "meta": summary_meta,
                "counts": {**stats, "pages": len(pages) + 1},
                "assets": {"css": css_href, "js": js},
                "media": {"photos": len(images.photos), "logos": len(images.logos)},
                "files": files,
            }
            write(stage, MANIFEST_NAME, dumps(manifest_doc, pretty=True))
            n_files, total, n_html, html_bytes = _measure(stage)
            if n_files > MAX_FILES:
                raise BuildError(f"site has {n_files:,} files (max {MAX_FILES:,})")
            if total > MAX_TOTAL:
                raise BuildError(f"site is {total / MiB:.1f} MiB (max {MAX_TOTAL // MiB} MiB)")
            for child in sorted(stage.iterdir()):
                child.rename(out / child.name)
            stage.rmdir()
        except BaseException:
            shutil.rmtree(stage, ignore_errors=True)
            if created and out.is_dir() and not any(out.iterdir()):
                out.rmdir()
            raise
    stats.update({"photos": len(images.photos), "logos": len(images.logos),
                  "og_cards": len(cards), "files": n_files, "bytes": total, "html_files": n_html,
                  "html_bytes": html_bytes, "pages": len(pages) + 1, "out": str(out),
                  "js": sorted(js)})
    return stats


__all__ = ["build", "BuildError", "MODES", "DEFAULT_DATA_BASE", "DEFAULT_SITE_URL",
           "render_headers", "file_index", "sha256_file", "MANIFEST_NAME", "HEADERS_NAME",
           "ASSETS_DIR", "copy_assets"]
