"""``web build``: render the site into a fresh ``--out`` directory.

Read-only on its inputs (AC-A3): the DB is opened ``mode=ro`` and nothing is written beside the
DB or the manifest. The site is staged in a hidden sibling of ``--out`` and renamed into place
only when complete. An ``--out`` that exists and is not empty is refused before anything is
written (exit 2).

Phase A writes the data layer (``data/*.json``, the per-page ``items.json``), ``_headers`` and
``web-manifest.json``. Pages arrive in phase B.
"""
from __future__ import annotations

import datetime as dt
import hashlib
import os
import shutil
from pathlib import Path
from urllib.parse import urlsplit

from . import WEB_BUNDLE_VERSION
from .bundle import dumps, write, write_data
from .dataset import Dataset, sha256_file

MODES = ("preview", "production")
DEFAULT_DATA_BASE = "https://data.kevinrassool.com/interests/"
MANIFEST_NAME = "web-manifest.json"
HEADERS_NAME = "_headers"
ASSETS_DIR = "assets"  # content-hashed JS/CSS (phase B); cached for a year


class BuildError(ValueError):
    """Bad input or clobber guard (exit 2)."""


def render_headers(mode: str) -> str:
    """Cloudflare ``_headers``: CORS on the static API, long cache on hashed assets, and
    ``noindex`` on every path in preview mode."""
    lines = [f"# Generated by python -m disclosures web build (mode: {mode}). Do not edit."]
    if mode == "preview":
        lines += ["/*", "  X-Robots-Tag: noindex, nofollow"]
    lines += [
        "/data/*", "  Access-Control-Allow-Origin: *",
        "/*/items.json", "  Access-Control-Allow-Origin: *",
        f"/{ASSETS_DIR}/*", "  Cache-Control: public, max-age=31536000, immutable",
    ]
    return "\n".join(lines) + "\n"


def file_index(root: Path, exclude=(MANIFEST_NAME,)) -> dict:
    """rel path -> {sha256, size} for every file under ``root``, sorted."""
    out = {}
    for p in sorted(root.rglob("*")):
        if p.is_file():
            rel = p.relative_to(root).as_posix()
            if rel in exclude:
                continue
            data = p.read_bytes()
            out[rel] = {"sha256": hashlib.sha256(data).hexdigest(), "size": len(data)}
    return out


def build_time() -> str:
    epoch = os.environ.get("SOURCE_DATE_EPOCH")
    t = (dt.datetime.fromtimestamp(int(epoch), dt.timezone.utc) if epoch
         else dt.datetime.now(dt.timezone.utc))
    return t.isoformat(timespec="seconds")


def _check_out(out: Path) -> None:
    if out.exists():
        if not out.is_dir():
            raise BuildError(f"--out {out} exists and is not a directory")
        if any(out.iterdir()):
            raise BuildError(f"--out {out} exists and is not empty; refusing to overwrite")


def _check_data_base(data_base: str) -> None:
    u = urlsplit(data_base)
    if u.scheme not in ("http", "https") or not u.netloc or not data_base.endswith("/"):
        raise BuildError(f"--data-base must be an http(s) URL ending in '/': {data_base!r}")


def build(db: str | Path, manifest: str | Path, out: str | Path, mode: str = "preview",
          data_base: str = DEFAULT_DATA_BASE) -> dict:
    db, manifest, out = Path(db), Path(manifest), Path(out)
    if mode not in MODES:
        raise BuildError(f"--mode must be one of {MODES}")
    _check_data_base(data_base)
    _check_out(out)
    with Dataset(db, manifest) as ds:
        # Fail on bad input (missing URL, unsafe id) before touching the filesystem.
        ds.documents()
        ds.members()
        ds.entities()
        out.parent.mkdir(parents=True, exist_ok=True)
        stage = out.parent / f".{out.name}.tmp-{os.getpid()}"
        if stage.exists():
            shutil.rmtree(stage)
        stage.mkdir()
        try:
            stats = write_data(ds, stage)
            write(stage, HEADERS_NAME, render_headers(mode).encode("utf-8"))
            files = file_index(stage)
            manifest_doc = {
                "web_bundle_version": WEB_BUNDLE_VERSION,
                "mode": mode,
                "built_at": build_time(),
                "data_base": data_base,
                "inputs": {
                    "db": {"name": db.name, "sha256": ds.db_sha256, "size": db.stat().st_size},
                    "manifest": {"name": manifest.name, "sha256": ds.manifest_sha256,
                                 "size": manifest.stat().st_size},
                },
                "meta": ds.meta(),
                "counts": stats,
                "files": files,
            }
            write(stage, MANIFEST_NAME, dumps(manifest_doc, pretty=True))
            _check_out(out)  # nothing appeared meanwhile
            if out.exists():
                out.rmdir()
            stage.rename(out)
        except BaseException:
            shutil.rmtree(stage, ignore_errors=True)
            raise
    stats["files"] = len(files) + 1
    stats["bytes"] = sum(f["size"] for f in files.values()) + (out / MANIFEST_NAME).stat().st_size
    stats["out"] = str(out)
    return stats


__all__ = ["build", "BuildError", "MODES", "DEFAULT_DATA_BASE", "render_headers",
           "file_index", "sha256_file", "MANIFEST_NAME", "HEADERS_NAME", "ASSETS_DIR"]
