"""Entities report and the AC-3.3 / AC-3.4 / AC-3.6 checks (T2.7).

``python -m disclosures entities --report [MD]`` writes the generated part of
``eval/entities_report.md``: method and entity-type counts, the AC-3.3 and AC-3.4 results, and
the v2 top 20 next to v1's top 20 (``disclosures.db``, opened read-only). Only the text between
the BEGIN/END markers is rewritten, so hand-written sections (the top-20 review, the G3 notes)
survive a refresh.
"""

from __future__ import annotations

import sqlite3
from collections import Counter
from pathlib import Path
from typing import List, Optional

from .entities import METHODS, newest_asx_snapshot, read_asx_snapshot
from .normalise import normalise_entity

DEFAULT_REPORT = "eval/entities_report.md"
V1_DB = "disclosures.db"
BEGIN = "<!-- BEGIN generated by `python -m disclosures entities --report`; edits here are lost -->"
END = "<!-- END generated -->"
AC34_METHODS = ("curated", "asx", "generic")


def ac33_unresolved(con: sqlite3.Connection) -> List[str]:
    """AC-3.3: raw names of items that have a name, no entity, and an alias that isn't generic.
    ``items`` doesn't store the normalised alias, so the join goes through ``normalise_entity``."""
    generic = {a for (a,) in con.execute(
        "select alias_normalised from entity_aliases where method = 'generic'")}
    return sorted(raw for (raw,) in con.execute(
        "select entity_name_raw from items where entity_name_raw is not null and entity_id is null")
        if normalise_entity(raw) not in generic)


def ac34_problems(con: sqlite3.Connection, reference_dir: Path) -> List[str]:
    """AC-3.4: one line per failure; empty means it passes. Every method in ``AC34_METHODS``
    has aliases, and every listed_company entity has an asx_code that's in the newest snapshot."""
    problems = []
    methods = dict(con.execute("select method, count(*) from entity_aliases group by 1"))
    problems += [f"no {m} aliases" for m in AC34_METHODS if not methods.get(m)]
    snap = newest_asx_snapshot(reference_dir)
    codes = {code for _, code in read_asx_snapshot(snap)} if snap else set()
    if snap is None:
        problems.append(f"no ASX snapshot in {reference_dir}")
    for eid, code in con.execute("select entity_id, asx_code from entities "
                                 "where entity_type = 'listed_company' order by 1"):
        if not code:
            problems.append(f"listed_company {eid} has no asx_code")
        elif snap is not None and code not in codes:
            problems.append(f"listed_company {eid} has asx_code {code}, not in {snap.name}")
    return problems


def top_v2(con: sqlite3.Connection, n: int = 20) -> List[tuple]:
    """(canonical_name, entity_type, asx_code, items), most items first, ties by name."""
    return con.execute(
        "select e.canonical_name, e.entity_type, e.asx_code, count(*) n from items i "
        "join entities e using (entity_id) group by e.entity_id "
        "order by n desc, e.canonical_name limit ?", (n,)).fetchall()


def top_v1(v1_path: Path, n: int = 20) -> List[tuple]:
    """v1's (canonical_name, disclosures), read-only; [] if the v1 DB isn't there."""
    if not Path(v1_path).exists():
        return []
    con = sqlite3.connect(f"file:{v1_path}?mode=ro", uri=True)
    try:
        return con.execute(
            "select e.canonical_name, count(*) n from disclosures d join entities e "
            "using (entity_id) group by e.entity_id order by n desc, e.canonical_name "
            "limit ?", (n,)).fetchall()
    finally:
        con.close()


def _table(header: List[str], rows: List[list]) -> List[str]:
    cell = lambda v: "" if v is None else str(v).replace("|", "\\|")  # noqa: E731
    out = ["| " + " | ".join(header) + " |", "|" + "|".join("---" for _ in header) + "|"]
    return out + ["| " + " | ".join(cell(v) for v in r) + " |" for r in rows]


def generate(db_path: Path, reference_dir: Path, v1_path: Path = Path(V1_DB)) -> str:
    """The generated block (markers included). Deterministic for a given DB and inputs."""
    con = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    try:
        named = con.execute("select count(*) from items where entity_name_raw is not null"
                            ).fetchone()[0]
        n_entities = con.execute("select count(*) from entities").fetchone()[0]
        aliases = dict(con.execute("select method, count(*) from entity_aliases group by 1"))
        # an item's method is its own alias's method (generic items have no entity)
        alias_method = dict(con.execute("select alias_normalised, method from entity_aliases"))
        method_items = Counter(alias_method.get(normalise_entity(raw)) for (raw,) in con.execute(
            "select entity_name_raw from items where entity_name_raw is not null"))
        types = con.execute(
            "select coalesce(e.entity_type, '(untyped)'), count(distinct e.entity_id), "
            "count(i.item_id) from entities e left join items i using (entity_id) "
            "group by 1 order by 3 desc, 1").fetchall()
        unresolved = ac33_unresolved(con)
        problems = ac34_problems(con, reference_dir)
        listed = con.execute("select count(*) from entities where entity_type = 'listed_company'"
                             ).fetchone()[0]
        coded = con.execute("select count(*) from entities where asx_code is not null"
                            ).fetchone()[0]
        v2 = top_v2(con)
    finally:
        con.close()
    snap = newest_asx_snapshot(reference_dir)
    v1 = top_v1(v1_path)

    L = [BEGIN, "", f"Built from `{Path(db_path).name}`: {named:,} named items -> "
         f"{n_entities:,} entities. ASX snapshot: `{snap.name if snap else 'none'}`.", "",
         "## Method counts", "",
         "An item counts under its own alias's method, so a ticker alias that joined a curated "
         "entity counts as asx.",
         ""]
    L += _table(["method", "aliases", "items"],
                [[m, f"{aliases.get(m, 0):,}", f"{method_items.get(m, 0):,}"] for m in METHODS])
    L += ["", "## Entity types", "",
          "`(untyped)` = singletons (one item, never typed: SPEC-DELTA D2).", ""]
    L += _table(["entity_type", "entities", "items"], [[t, f"{e:,}", f"{i:,}"]
                                                       for t, e, i in types])
    L += ["", "## AC-3.3: non-generic named items without an entity", "",
          "```sql", "select count(*) from items where entity_name_raw is not null",
          "  and entity_id is null",
          "  and normalise_entity(entity_name_raw) not in",
          "      (select alias_normalised from entity_aliases where method = 'generic')", "```",
          "", f"Result: **{len(unresolved)}** ({'PASS' if not unresolved else 'FAIL'})."]
    L += [f"- `{r}`" for r in unresolved[:20]]
    L += ["", "## AC-3.4: methods and ASX codes", "",
          "```sql", "select method, count(*) from entity_aliases group by 1;",
          "select entity_id, asx_code from entities where entity_type = 'listed_company';",
          "```", "",
          "- " + ", ".join(f"{m} {aliases.get(m, 0):,}" for m in AC34_METHODS)
          + " aliases (each must be > 0).",
          f"- {listed:,} listed_company entities, each with an asx_code in the snapshot "
          f"({coded:,} entities carry a code in all; banks, airlines and the like keep their "
          f"own type).",
          f"- Result: **{'PASS' if not problems else 'FAIL'}**."]
    L += [f"  - {p}" for p in problems[:20]]
    L += ["", "## AC-3.6: top 20 entities by item count, v2 next to v1", "",
          "v1 counts are `disclosures` rows per v1 entity (`disclosures.db`, read-only); v1 never "
          "merged spellings, so the same organisation recurs (QANTAS, Virgin / Virgin Australia "
          "Airlines Pty Ltd, NAB / NATIONAL AUSTRALIA BANK, CBA / Commonwealth bank).", ""]
    rows = []
    for k in range(max(len(v2), len(v1))):
        a = v2[k] if k < len(v2) else (None,) * 4
        b = v1[k] if k < len(v1) else (None, None)
        rows.append([k + 1, a[0], a[1], a[2], f"{a[3]:,}" if a[3] else "", b[0],
                     f"{b[1]:,}" if b[1] else ""])
    L += _table(["#", "v2 entity", "type", "ASX", "v2 items", "v1 entity", "v1 rows"], rows)
    L += ["", END]
    return "\n".join(L) + "\n"


def write_report(db_path: Path, reference_dir: Path, out: Path = Path(DEFAULT_REPORT),
                 v1_path: Path = Path(V1_DB)) -> Path:
    """Replace the generated block in ``out`` (or create the file with a title)."""
    block = generate(Path(db_path), Path(reference_dir), Path(v1_path))
    out = Path(out)
    if out.exists():
        text = out.read_text(encoding="utf-8")
        if BEGIN in text and END in text:
            head, rest = text.split(BEGIN, 1)
            tail = rest.split(END, 1)[1].lstrip("\n")
            text = head + block + ("\n" + tail if tail else "")
        else:
            text = text.rstrip("\n") + "\n\n" + block
    else:
        text = "# Entities report (Phase 3)\n\n" + block
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    return out
